import { defineConfig } from 'drizzle-kit';

// Used only by `npm run db:pull` (introspection). Schema changes are hand-written
// numbered files in db/migrations/, never generated by drizzle-kit push/migrate.
export default defineConfig({
  dialect: 'postgresql',
  out: './db/introspected',
  schema: './api/_lib/schema.ts',
  dbCredentials: { url: process.env.DATABASE_URL_UNPOOLED! },
  schemaFilter: ['public'],
});
