// GENERATED by `npm run db:pull` from the live database. Do not edit by hand.
// Change the database with a numbered file in db/migrations/, then re-run db:pull.
import { relations } from "drizzle-orm/relations";
import { household, householdMember, users, paymentMethod, chore, choreAssignment, choreSwapRequest, event, wishlistItem, recurringBill, expense, payment, bulletinMessage, notification, appFeedback, choreRotation, eventTag, expenseShare } from "./schema.js";

export const householdMemberRelations = relations(householdMember, ({one}) => ({
	household: one(household, {
		fields: [householdMember.householdId],
		references: [household.householdId]
	}),
	user: one(users, {
		fields: [householdMember.userId],
		references: [users.userId]
	}),
}));

export const householdRelations = relations(household, ({many}) => ({
	householdMembers: many(householdMember),
	chores: many(chore),
	events: many(event),
	wishlistItems: many(wishlistItem),
	recurringBills: many(recurringBill),
	expenses: many(expense),
	payments: many(payment),
	bulletinMessages: many(bulletinMessage),
	notifications: many(notification),
}));

export const usersRelations = relations(users, ({many}) => ({
	householdMembers: many(householdMember),
	paymentMethods: many(paymentMethod),
	chores: many(chore),
	choreAssignments: many(choreAssignment),
	events: many(event),
	wishlistItems: many(wishlistItem),
	expenses: many(expense),
	payments_payerUserId: many(payment, {
		relationName: "payment_payerUserId_users_userId"
	}),
	payments_payeeUserId: many(payment, {
		relationName: "payment_payeeUserId_users_userId"
	}),
	bulletinMessages: many(bulletinMessage),
	notifications_actorUserId: many(notification, {
		relationName: "notification_actorUserId_users_userId"
	}),
	notifications_userId: many(notification, {
		relationName: "notification_userId_users_userId"
	}),
	appFeedbacks: many(appFeedback),
	choreRotations: many(choreRotation),
	eventTags: many(eventTag),
	expenseShares: many(expenseShare),
}));

export const paymentMethodRelations = relations(paymentMethod, ({one}) => ({
	user: one(users, {
		fields: [paymentMethod.userId],
		references: [users.userId]
	}),
}));

export const choreRelations = relations(chore, ({one, many}) => ({
	household: one(household, {
		fields: [chore.householdId],
		references: [household.householdId]
	}),
	user: one(users, {
		fields: [chore.createdByUserId],
		references: [users.userId]
	}),
	choreAssignments: many(choreAssignment),
	choreRotations: many(choreRotation),
}));

export const choreAssignmentRelations = relations(choreAssignment, ({one, many}) => ({
	chore: one(chore, {
		fields: [choreAssignment.choreId],
		references: [chore.choreId]
	}),
	user: one(users, {
		fields: [choreAssignment.assignedUserId],
		references: [users.userId]
	}),
	choreSwapRequests_requesterAssignmentId: many(choreSwapRequest, {
		relationName: "choreSwapRequest_requesterAssignmentId_choreAssignment_assignmentId"
	}),
	choreSwapRequests_targetAssignmentId: many(choreSwapRequest, {
		relationName: "choreSwapRequest_targetAssignmentId_choreAssignment_assignmentId"
	}),
}));

export const choreSwapRequestRelations = relations(choreSwapRequest, ({one}) => ({
	choreAssignment_requesterAssignmentId: one(choreAssignment, {
		fields: [choreSwapRequest.requesterAssignmentId],
		references: [choreAssignment.assignmentId],
		relationName: "choreSwapRequest_requesterAssignmentId_choreAssignment_assignmentId"
	}),
	choreAssignment_targetAssignmentId: one(choreAssignment, {
		fields: [choreSwapRequest.targetAssignmentId],
		references: [choreAssignment.assignmentId],
		relationName: "choreSwapRequest_targetAssignmentId_choreAssignment_assignmentId"
	}),
}));

export const eventRelations = relations(event, ({one, many}) => ({
	household: one(household, {
		fields: [event.householdId],
		references: [household.householdId]
	}),
	user: one(users, {
		fields: [event.createdByUserId],
		references: [users.userId]
	}),
	bulletinMessages: many(bulletinMessage),
	eventTags: many(eventTag),
}));

export const wishlistItemRelations = relations(wishlistItem, ({one, many}) => ({
	household: one(household, {
		fields: [wishlistItem.householdId],
		references: [household.householdId]
	}),
	user: one(users, {
		fields: [wishlistItem.createdByUserId],
		references: [users.userId]
	}),
	expenses: many(expense),
}));

export const recurringBillRelations = relations(recurringBill, ({one, many}) => ({
	household: one(household, {
		fields: [recurringBill.householdId],
		references: [household.householdId]
	}),
	expenses: many(expense),
}));

export const expenseRelations = relations(expense, ({one, many}) => ({
	household: one(household, {
		fields: [expense.householdId],
		references: [household.householdId]
	}),
	user: one(users, {
		fields: [expense.paidByUserId],
		references: [users.userId]
	}),
	wishlistItem: one(wishlistItem, {
		fields: [expense.wishlistItemId],
		references: [wishlistItem.wishlistItemId]
	}),
	recurringBill: one(recurringBill, {
		fields: [expense.billId],
		references: [recurringBill.billId]
	}),
	expenseShares: many(expenseShare),
}));

export const paymentRelations = relations(payment, ({one, many}) => ({
	household: one(household, {
		fields: [payment.householdId],
		references: [household.householdId]
	}),
	user_payerUserId: one(users, {
		fields: [payment.payerUserId],
		references: [users.userId],
		relationName: "payment_payerUserId_users_userId"
	}),
	user_payeeUserId: one(users, {
		fields: [payment.payeeUserId],
		references: [users.userId],
		relationName: "payment_payeeUserId_users_userId"
	}),
	expenseShares: many(expenseShare),
}));

export const bulletinMessageRelations = relations(bulletinMessage, ({one, many}) => ({
	household: one(household, {
		fields: [bulletinMessage.householdId],
		references: [household.householdId]
	}),
	user: one(users, {
		fields: [bulletinMessage.senderUserId],
		references: [users.userId]
	}),
	event: one(event, {
		fields: [bulletinMessage.eventId],
		references: [event.eventId]
	}),
	bulletinMessage: one(bulletinMessage, {
		fields: [bulletinMessage.parentMessageId],
		references: [bulletinMessage.messageId],
		relationName: "bulletinMessage_parentMessageId_bulletinMessage_messageId"
	}),
	bulletinMessages: many(bulletinMessage, {
		relationName: "bulletinMessage_parentMessageId_bulletinMessage_messageId"
	}),
}));

export const notificationRelations = relations(notification, ({one}) => ({
	user_actorUserId: one(users, {
		fields: [notification.actorUserId],
		references: [users.userId],
		relationName: "notification_actorUserId_users_userId"
	}),
	user_userId: one(users, {
		fields: [notification.userId],
		references: [users.userId],
		relationName: "notification_userId_users_userId"
	}),
	household: one(household, {
		fields: [notification.householdId],
		references: [household.householdId]
	}),
}));

export const appFeedbackRelations = relations(appFeedback, ({one}) => ({
	user: one(users, {
		fields: [appFeedback.userId],
		references: [users.userId]
	}),
}));

export const choreRotationRelations = relations(choreRotation, ({one}) => ({
	chore: one(chore, {
		fields: [choreRotation.choreId],
		references: [chore.choreId]
	}),
	user: one(users, {
		fields: [choreRotation.userId],
		references: [users.userId]
	}),
}));

export const eventTagRelations = relations(eventTag, ({one}) => ({
	event: one(event, {
		fields: [eventTag.eventId],
		references: [event.eventId]
	}),
	user: one(users, {
		fields: [eventTag.userId],
		references: [users.userId]
	}),
}));

export const expenseShareRelations = relations(expenseShare, ({one}) => ({
	expense: one(expense, {
		fields: [expenseShare.expenseId],
		references: [expense.expenseId]
	}),
	user: one(users, {
		fields: [expenseShare.userId],
		references: [users.userId]
	}),
	payment: one(payment, {
		fields: [expenseShare.settledByPaymentId],
		references: [payment.paymentId]
	}),
}));