// GENERATED by `npm run db:pull` from the live database. Do not edit by hand.
// Change the database with a numbered file in db/migrations/, then re-run db:pull.
import { pgTable, unique, bigint, text, timestamp, index, foreignKey, check, boolean, date, smallint, time, integer, numeric, primaryKey } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const household = pgTable("household", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	householdId: bigint("household_id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "household_household_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	householdName: text("household_name").notNull(),
	address: text(),
	joinCode: text("join_code").notNull(),
	themeColor: text("theme_color"),
	timezone: text().default('America/Denver').notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("household_join_code_key").on(table.joinCode),
]);

export const householdMember = pgTable("household_member", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	memberId: bigint("member_id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "household_member_member_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	householdId: bigint("household_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).notNull(),
	role: text().default('member').notNull(),
	joinedDate: timestamp("joined_date", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	leftDate: timestamp("left_date", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_household_member_active").using("btree", table.householdId.asc().nullsLast().op("int8_ops")).where(sql`(left_date IS NULL)`),
	index("idx_household_member_user").using("btree", table.userId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.householdId],
			foreignColumns: [household.householdId],
			name: "household_member_household_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.userId],
			name: "household_member_user_id_fkey"
		}).onDelete("cascade"),
	unique("household_member_household_id_user_id_key").on(table.householdId, table.userId),
	check("household_member_role_check", sql`role = ANY (ARRAY['owner'::text, 'member'::text])`),
	check("household_member_check", sql`(left_date IS NULL) OR (left_date >= joined_date)`),
]);

export const users = pgTable("users", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "users_user_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	authProviderId: text("auth_provider_id"),
	firstName: text("first_name").notNull(),
	lastName: text("last_name").notNull(),
	email: text().notNull(),
	phoneNumber: text("phone_number"),
	profilePhoto: text("profile_photo"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("users_auth_provider_id_key").on(table.authProviderId),
	unique("users_email_key").on(table.email),
]);

export const paymentMethod = pgTable("payment_method", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	paymentMethodId: bigint("payment_method_id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "payment_method_payment_method_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).notNull(),
	app: text().notNull(),
	username: text().notNull(),
	isPreferred: boolean("is_preferred").default(false).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.userId],
			name: "payment_method_user_id_fkey"
		}).onDelete("cascade"),
	check("payment_method_app_check", sql`app = ANY (ARRAY['venmo'::text, 'zelle'::text, 'apple_cash'::text])`),
]);

export const chore = pgTable("chore", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	choreId: bigint("chore_id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "chore_chore_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	householdId: bigint("household_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdByUserId: bigint("created_by_user_id", { mode: "number" }),
	choreName: text("chore_name").notNull(),
	description: text(),
	repeats: text().default('none').notNull(),
	startDate: date("start_date").default(sql`CURRENT_DATE`).notNull(),
	dayOfWeek: smallint("day_of_week"),
	dayOfMonth: smallint("day_of_month"),
	dueTime: time("due_time"),
	effort: text().default('medium').notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_chore_household").using("btree", table.householdId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.householdId],
			foreignColumns: [household.householdId],
			name: "chore_household_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.createdByUserId],
			foreignColumns: [users.userId],
			name: "chore_created_by_user_id_fkey"
		}).onDelete("set null"),
	check("chore_repeats_check", sql`repeats = ANY (ARRAY['none'::text, 'weekly'::text, 'monthly'::text])`),
	check("chore_day_of_week_check", sql`(day_of_week >= 0) AND (day_of_week <= 6)`),
	check("chore_day_of_month_check", sql`(day_of_month >= 1) AND (day_of_month <= 31)`),
	check("chore_effort_check", sql`effort = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text])`),
	check("chore_check", sql`((repeats = 'none'::text) AND (day_of_week IS NULL) AND (day_of_month IS NULL)) OR ((repeats = 'weekly'::text) AND (day_of_week IS NOT NULL) AND (day_of_month IS NULL)) OR ((repeats = 'monthly'::text) AND (day_of_month IS NOT NULL) AND (day_of_week IS NULL))`),
]);

export const choreAssignment = pgTable("chore_assignment", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	assignmentId: bigint("assignment_id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "chore_assignment_assignment_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	choreId: bigint("chore_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	assignedUserId: bigint("assigned_user_id", { mode: "number" }).notNull(),
	dueAt: timestamp("due_at", { withTimezone: true, mode: 'string' }).notNull(),
	isCompleted: boolean("is_completed").default(false).notNull(),
	completedAt: timestamp("completed_at", { withTimezone: true, mode: 'string' }),
	lastRemindedAt: timestamp("last_reminded_at", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_chore_assignment_user").using("btree", table.assignedUserId.asc().nullsLast().op("timestamptz_ops"), table.dueAt.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.choreId],
			foreignColumns: [chore.choreId],
			name: "chore_assignment_chore_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.assignedUserId],
			foreignColumns: [users.userId],
			name: "chore_assignment_assigned_user_id_fkey"
		}).onDelete("cascade"),
	unique("chore_assignment_chore_id_due_at_key").on(table.choreId, table.dueAt),
	check("chore_assignment_check", sql`is_completed = (completed_at IS NOT NULL)`),
]);

export const choreSwapRequest = pgTable("chore_swap_request", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	swapId: bigint("swap_id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "chore_swap_request_swap_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	requesterAssignmentId: bigint("requester_assignment_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	targetAssignmentId: bigint("target_assignment_id", { mode: "number" }),
	type: text().notNull(),
	requestMessage: text("request_message"),
	status: text().default('pending').notNull(),
	responseMessage: text("response_message"),
	requestedDate: timestamp("requested_date", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	respondedDate: timestamp("responded_date", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_swap_target").using("btree", table.targetAssignmentId.asc().nullsLast().op("int8_ops")).where(sql`(status = 'pending'::text)`),
	foreignKey({
			columns: [table.requesterAssignmentId],
			foreignColumns: [choreAssignment.assignmentId],
			name: "chore_swap_request_requester_assignment_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.targetAssignmentId],
			foreignColumns: [choreAssignment.assignmentId],
			name: "chore_swap_request_target_assignment_id_fkey"
		}).onDelete("cascade"),
	check("chore_swap_request_check1", sql`requester_assignment_id IS DISTINCT FROM target_assignment_id`),
	check("chore_swap_request_type_check", sql`type = ANY (ARRAY['swap'::text, 'skip'::text])`),
	check("chore_swap_request_status_check", sql`status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text])`),
	check("chore_swap_request_check", sql`((type = 'swap'::text) AND (target_assignment_id IS NOT NULL)) OR ((type = 'skip'::text) AND (target_assignment_id IS NULL))`),
	check("chore_swap_request_check2", sql`(status = 'pending'::text) = (responded_date IS NULL)`),
]);

export const event = pgTable("event", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	eventId: bigint("event_id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "event_event_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	householdId: bigint("household_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdByUserId: bigint("created_by_user_id", { mode: "number" }),
	eventName: text("event_name").notNull(),
	eventDate: timestamp("event_date", { withTimezone: true, mode: 'string' }).notNull(),
	endDate: timestamp("end_date", { withTimezone: true, mode: 'string' }),
	location: text(),
	category: text().default('other').notNull(),
	color: text(),
	reminderMinutesBefore: integer("reminder_minutes_before"),
	description: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_event_household_date").using("btree", table.householdId.asc().nullsLast().op("int8_ops"), table.eventDate.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.householdId],
			foreignColumns: [household.householdId],
			name: "event_household_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.createdByUserId],
			foreignColumns: [users.userId],
			name: "event_created_by_user_id_fkey"
		}).onDelete("set null"),
	check("event_category_check", sql`category = ANY (ARRAY['hosting'::text, 'meeting'::text, 'other'::text])`),
	check("event_reminder_minutes_before_check", sql`reminder_minutes_before >= 0`),
	check("event_check", sql`(end_date IS NULL) OR (end_date >= event_date)`),
]);

export const wishlistItem = pgTable("wishlist_item", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	wishlistItemId: bigint("wishlist_item_id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wishlist_item_wishlist_item_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	householdId: bigint("household_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdByUserId: bigint("created_by_user_id", { mode: "number" }),
	itemName: text("item_name").notNull(),
	needOrWant: text("need_or_want").notNull(),
	estimatedPrice: numeric("estimated_price", { precision: 10, scale:  2 }),
	itemLink: text("item_link"),
	description: text(),
	isBought: boolean("is_bought").default(false).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_wishlist_household").using("btree", table.householdId.asc().nullsLast().op("int8_ops")).where(sql`(NOT is_bought)`),
	foreignKey({
			columns: [table.householdId],
			foreignColumns: [household.householdId],
			name: "wishlist_item_household_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.createdByUserId],
			foreignColumns: [users.userId],
			name: "wishlist_item_created_by_user_id_fkey"
		}).onDelete("set null"),
	check("wishlist_item_need_or_want_check", sql`need_or_want = ANY (ARRAY['need'::text, 'want'::text])`),
	check("wishlist_item_estimated_price_check", sql`estimated_price >= (0)::numeric`),
]);

export const recurringBill = pgTable("recurring_bill", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	billId: bigint("bill_id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "recurring_bill_bill_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	householdId: bigint("household_id", { mode: "number" }).notNull(),
	billName: text("bill_name").notNull(),
	billType: text("bill_type").notNull(),
	amount: numeric({ precision: 10, scale:  2 }).notNull(),
	dueDayOfMonth: smallint("due_day_of_month").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.householdId],
			foreignColumns: [household.householdId],
			name: "recurring_bill_household_id_fkey"
		}).onDelete("cascade"),
	check("recurring_bill_bill_type_check", sql`bill_type = ANY (ARRAY['rent'::text, 'utility'::text, 'subscription'::text])`),
	check("recurring_bill_amount_check", sql`amount >= (0)::numeric`),
	check("recurring_bill_due_day_of_month_check", sql`(due_day_of_month >= 1) AND (due_day_of_month <= 31)`),
]);

export const expense = pgTable("expense", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	expenseId: bigint("expense_id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "expense_expense_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	householdId: bigint("household_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	paidByUserId: bigint("paid_by_user_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	wishlistItemId: bigint("wishlist_item_id", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	billId: bigint("bill_id", { mode: "number" }),
	itemName: text("item_name").notNull(),
	totalAmount: numeric("total_amount", { precision: 10, scale:  2 }).notNull(),
	purchaseDate: date("purchase_date").default(sql`CURRENT_DATE`).notNull(),
	receiptPhoto: text("receipt_photo"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_expense_household").using("btree", table.householdId.asc().nullsLast().op("date_ops"), table.purchaseDate.asc().nullsLast().op("date_ops")),
	foreignKey({
			columns: [table.householdId],
			foreignColumns: [household.householdId],
			name: "expense_household_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.paidByUserId],
			foreignColumns: [users.userId],
			name: "expense_paid_by_user_id_fkey"
		}).onDelete("restrict"),
	foreignKey({
			columns: [table.wishlistItemId],
			foreignColumns: [wishlistItem.wishlistItemId],
			name: "expense_wishlist_item_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.billId],
			foreignColumns: [recurringBill.billId],
			name: "expense_bill_id_fkey"
		}).onDelete("set null"),
	unique("expense_wishlist_item_id_key").on(table.wishlistItemId),
	check("expense_total_amount_check", sql`total_amount >= (0)::numeric`),
]);

export const payment = pgTable("payment", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	paymentId: bigint("payment_id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "payment_payment_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	householdId: bigint("household_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	payerUserId: bigint("payer_user_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	payeeUserId: bigint("payee_user_id", { mode: "number" }).notNull(),
	amount: numeric({ precision: 10, scale:  2 }).notNull(),
	paidWith: text("paid_with").notNull(),
	status: text().default('sent').notNull(),
	paidDate: timestamp("paid_date", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_payment_household").using("btree", table.householdId.asc().nullsLast().op("int8_ops"), table.paidDate.asc().nullsLast().op("int8_ops")),
	index("idx_payment_payee").using("btree", table.payeeUserId.asc().nullsLast().op("int8_ops")),
	index("idx_payment_payer").using("btree", table.payerUserId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.householdId],
			foreignColumns: [household.householdId],
			name: "payment_household_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.payerUserId],
			foreignColumns: [users.userId],
			name: "payment_payer_user_id_fkey"
		}).onDelete("restrict"),
	foreignKey({
			columns: [table.payeeUserId],
			foreignColumns: [users.userId],
			name: "payment_payee_user_id_fkey"
		}).onDelete("restrict"),
	check("payment_amount_check", sql`amount > (0)::numeric`),
	check("payment_paid_with_check", sql`paid_with = ANY (ARRAY['venmo'::text, 'zelle'::text, 'apple_cash'::text])`),
	check("payment_status_check", sql`status = ANY (ARRAY['sent'::text, 'confirmed'::text, 'disputed'::text])`),
	check("payment_check", sql`payer_user_id <> payee_user_id`),
]);

export const bulletinMessage = pgTable("bulletin_message", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	messageId: bigint("message_id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "bulletin_message_message_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	householdId: bigint("household_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	senderUserId: bigint("sender_user_id", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	eventId: bigint("event_id", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	parentMessageId: bigint("parent_message_id", { mode: "number" }),
	messageText: text("message_text").notNull(),
	isPinned: boolean("is_pinned").default(false).notNull(),
	postedDate: timestamp("posted_date", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_bulletin_event").using("btree", table.eventId.asc().nullsLast().op("int8_ops")),
	index("idx_bulletin_household").using("btree", table.householdId.asc().nullsLast().op("timestamptz_ops"), table.postedDate.desc().nullsFirst().op("int8_ops")),
	index("idx_bulletin_parent").using("btree", table.parentMessageId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.householdId],
			foreignColumns: [household.householdId],
			name: "bulletin_message_household_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.senderUserId],
			foreignColumns: [users.userId],
			name: "bulletin_message_sender_user_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.eventId],
			foreignColumns: [event.eventId],
			name: "bulletin_message_event_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.parentMessageId],
			foreignColumns: [table.messageId],
			name: "bulletin_message_parent_message_id_fkey"
		}).onDelete("cascade"),
]);

export const notification = pgTable("notification", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	notificationId: bigint("notification_id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "notification_notification_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	householdId: bigint("household_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	actorUserId: bigint("actor_user_id", { mode: "number" }),
	section: text().notNull(),
	sourceType: text("source_type"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	sourceId: bigint("source_id", { mode: "number" }),
	message: text().notNull(),
	isRead: boolean("is_read").default(false).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_notification_source").using("btree", table.sourceType.asc().nullsLast().op("int8_ops"), table.sourceId.asc().nullsLast().op("int8_ops")),
	index("idx_notification_user").using("btree", table.userId.asc().nullsLast().op("bool_ops"), table.isRead.asc().nullsLast().op("timestamptz_ops"), table.createdAt.desc().nullsFirst().op("bool_ops")),
	foreignKey({
			columns: [table.actorUserId],
			foreignColumns: [users.userId],
			name: "notification_actor_user_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.userId],
			name: "notification_user_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.householdId],
			foreignColumns: [household.householdId],
			name: "notification_household_id_fkey"
		}).onDelete("cascade"),
	check("notification_check", sql`(source_type IS NULL) = (source_id IS NULL)`),
	check("notification_section_check", sql`section = ANY (ARRAY['chores'::text, 'money'::text, 'expense_tracker'::text, 'system'::text, 'calendar_board'::text])`),
	check("notification_source_type_check", sql`source_type = ANY (ARRAY['chore_assignment'::text, 'chore_swap_request'::text, 'expense'::text, 'expense_share'::text, 'payment'::text, 'wishlist_item'::text, 'event'::text, 'bulletin_message'::text])`),
]);

export const appFeedback = pgTable("app_feedback", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	feedbackId: bigint("feedback_id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "app_feedback_feedback_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }),
	type: text().notNull(),
	rating: smallint(),
	message: text(),
	submittedDate: timestamp("submitted_date", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.userId],
			name: "app_feedback_user_id_fkey"
		}).onDelete("set null"),
	check("app_feedback_type_check", sql`type = ANY (ARRAY['bug'::text, 'idea'::text, 'other'::text])`),
	check("app_feedback_rating_check", sql`(rating >= 1) AND (rating <= 5)`),
]);

export const choreRotation = pgTable("chore_rotation", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	choreId: bigint("chore_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).notNull(),
	turnOrder: integer("turn_order").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.choreId],
			foreignColumns: [chore.choreId],
			name: "chore_rotation_chore_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.userId],
			name: "chore_rotation_user_id_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.choreId, table.userId], name: "chore_rotation_pkey"}),
	unique("chore_rotation_chore_id_turn_order_key").on(table.choreId, table.turnOrder),
]);

export const eventTag = pgTable("event_tag", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	eventId: bigint("event_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).notNull(),
	response: text(),
	respondedDate: timestamp("responded_date", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_event_tag_user").using("btree", table.userId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.eventId],
			foreignColumns: [event.eventId],
			name: "event_tag_event_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.userId],
			name: "event_tag_user_id_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.eventId, table.userId], name: "event_tag_pkey"}),
	check("event_tag_response_check", sql`response = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text])`),
]);

export const expenseShare = pgTable("expense_share", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	expenseId: bigint("expense_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).notNull(),
	amountOwed: numeric("amount_owed", { precision: 10, scale:  2 }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	settledByPaymentId: bigint("settled_by_payment_id", { mode: "number" }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_expense_share_payment").using("btree", table.settledByPaymentId.asc().nullsLast().op("int8_ops")),
	index("idx_expense_share_user").using("btree", table.userId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.expenseId],
			foreignColumns: [expense.expenseId],
			name: "expense_share_expense_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.userId],
			name: "expense_share_user_id_fkey"
		}).onDelete("restrict"),
	foreignKey({
			columns: [table.settledByPaymentId],
			foreignColumns: [payment.paymentId],
			name: "expense_share_settled_by_payment_id_fkey"
		}).onDelete("set null"),
	primaryKey({ columns: [table.expenseId, table.userId], name: "expense_share_pkey"}),
	check("expense_share_amount_owed_check", sql`amount_owed >= (0)::numeric`),
]);
