// After `drizzle-kit pull`: copy the generated types into api/_lib and discard the
// generated SQL (db/schema.sql + db/migrations are the only SQL that ever runs).
import { copyFileSync, readFileSync, rmSync, writeFileSync } from 'node:fs';

const banner = '// GENERATED by `npm run db:pull` from the live database. Do not edit by hand.\n// Change the database with a numbered file in db/migrations/, then re-run db:pull.\n';
for (const f of ['schema.ts', 'relations.ts']) {
  copyFileSync(`db/introspected/${f}`, `api/_lib/${f}`);
  // NodeNext needs explicit extensions on relative imports
  const code = readFileSync(`api/_lib/${f}`, 'utf8').replace(/from "\.\/schema"/g, 'from "./schema.js"');
  writeFileSync(`api/_lib/${f}`, banner + code);
}
rmSync('db/introspected', { recursive: true, force: true });
console.log('synced api/_lib/schema.ts and api/_lib/relations.ts');
